fix: custom readiness probe with custom healthCheck path not working (#8831)
* Fix custom readiness probe

* Adding argocd kube2e tests

* Adding cleanup job

* Adding changelog

* Cleanup

* make-all

* Moving changelog

* Fixes

* Fix cleanup

* Add comments

* Re-add cleanup job

* Fix argocd test

* Adding changelog file to new location

* Deleting changelog file from old location

* Adding changelog file to new location

* Deleting changelog file from old location

* Address docs comments

---------

Co-authored-by: soloio-bulldozer[bot] <48420018+soloio-bulldozer[bot]@users.noreply.github.com>
Co-authored-by: changelog-bot <changelog-bot>

diff --git a/install/helm/gloo/templates/5-resource-rollout-job.yaml b/install/helm/gloo/templates/5-resource-rollout-job.yaml
--- a/install/helm/gloo/templates/5-resource-rollout-job.yaml
+++ b/install/helm/gloo/templates/5-resource-rollout-job.yaml
@@ -12,9 +12,12 @@ metadata:
   name: gloo-resource-rollout
   namespace: {{ .Release.Namespace }}
   annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "5" # run this job after the role/rolebinding is created
-    {{- include "gloo.jobHelmDeletePolicySucceededAndBeforeCreation" .Values.gateway.rolloutJob | nindent 4 }}
+    # Argo checks the status of resources in an app to determine its state. Since a job is cleaned up (deleted) after ttlSecondsAfterFinished,
+    # the missing job causes the argo app to go out of sync.
+    # Annotating this job as a Sync hook along with an argo-specific hook deletion policy ensures that even when the job is cleaned up,
+    # it does not alter the state of the argo app and that it is still in sync.
+    argocd.argoproj.io/hook: Sync
+    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
 spec:
   {{- include "gloo.jobSpecStandardFields" .Values.gateway.rolloutJob | nindent 2 -}}
   template:
@@ -77,6 +80,22 @@ spec:
             kubectl rollout status deployment -n {{ .Release.Namespace }} gloo
             {{- end }}
 
+            # Wait for the enterprise job if present
+            kubectl -n {{ .Release.Namespace }} get job gloo-ee-resource-rollout &> /dev/null
+            if [ $? -eq 0 ]
+            then
+              # Exit immediately if the enterprise rollout job failed
+              kubectl -n {{ .Release.Namespace }} get job gloo-ee-resource-rollout -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -i "True" &> /dev/null
+              if [ $? -eq 0 ]
+              then
+                  echo "Enterprise rollout job failed"
+                  exit 1
+              fi
+
+              echo "Waiting for the enterprise resource rollout job to complete"
+              kubectl -n {{ .Release.Namespace }} wait --for=condition=complete job gloo-ee-resource-rollout --timeout={{ .Values.gateway.rolloutJob.timeout }}s || exit 1
+            fi
+
             # apply Gloo Edge custom resources
             if [ $HAS_CUSTOM_RESOURCES == "true" ]
             then
@@ -98,10 +117,6 @@ metadata:
   labels:
     app: gloo
     gloo: rbac
-  annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "0" # must be created before rollout job
-    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
   name: gloo-resource-rollout
   namespace: {{ .Release.Namespace }}
 ---
@@ -113,10 +128,6 @@ metadata:
   labels:
     app: gloo
     gloo: rbac
-  annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "0" # must be created before rollout job
-    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 rules:
 - apiGroups: ["apps"]
   resources: ["deployments"]
@@ -133,10 +144,6 @@ metadata:
   labels:
     app: gloo
     gloo: rbac
-  annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "0" # must be created before rollout job
-    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 roleRef:
   kind: Role
   name: gloo-resource-rollout
@@ -153,14 +160,14 @@ metadata:
   labels:
     app: gloo
     gloo: rbac
-  annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "0" # must be created before rollout job
-    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 rules:
 - apiGroups: ["gateway.solo.io"]
   resources: ["*"]
   verbs: ["get", "list", "create", "update", "patch"]
+# This permission is required by the oss rollout job in order to wait for the enterprise rollout job to finish first
+- apiGroups: ["batch"]
+  resources: ["jobs"]
+  verbs: ["get", "list", "watch", "delete"]
 ---
 kind: ClusterRoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
@@ -169,10 +176,6 @@ metadata:
   labels:
     app: gloo
     gloo: rbac
-  annotations:
-    "helm.sh/hook": post-install,post-upgrade
-    "helm.sh/hook-weight": "0" # must be created before rollout job
-    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 roleRef:
   kind: ClusterRole
   name: gloo-resource-rollout{{ include "gloo.rbacNameSuffix" . }}
